# Generated by Django 4.2.28 on 2026-02-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Liste de courses', max_length=200, verbose_name='Titre')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('completed', 'Terminée'), ('archived', 'Archivée')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Générée automatiquement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste de courses',
                'verbose_name_plural': 'Listes de courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité suggérée')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité achetée')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('reason', models.CharField(choices=[('below_threshold', 'Sous le seuil'), ('out_of_stock', 'Rupture de stock'), ('expiring_soon', 'Expire bientôt'), ('manual', 'Ajout manuel')], default='manual', max_length=30, verbose_name='Raison')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût réel')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Coché')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='products.product', verbose_name='Produit')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist', verbose_name='Liste')),
            ],
            options={
                'verbose_name': 'Article de liste',
                'verbose_name_plural': 'Articles de liste',
                'ordering': ['-priority', 'product__category', 'product__name'],
                'unique_together': {('shopping_list', 'product')},
            },
        ),
    ]
