# Generated by Django 4.2.28 on 2026-02-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'achat")),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat")),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur/Magasin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='products.location', verbose_name='Emplacement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'verbose_name_plural': 'Lots de stock',
                'ordering': ['expiry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUST', 'Ajustement')], max_length=10, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stocks.stockbatch', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('EXPIRING_SOON', 'Expire bientôt'), ('EXPIRED', 'Expiré')], max_length=20, verbose_name="Type d'alerte")),
                ('alert_date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'alerte")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stockbatch', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Alerte de péremption',
                'verbose_name_plural': 'Alertes de péremption',
                'ordering': ['-alert_date'],
            },
        ),
    ]
