# Generated by Django 4.2.28 on 2026-02-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nourriture', 'Nourriture'), ('boisson', 'Boisson'), ('epices', 'Épices'), ('menage', 'Ménage'), ('hygiene', 'Hygiène'), ('autre', 'Autre')], max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, help_text="Emoji ou classe d'icône", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#6B7280', help_text='Code hexadécimal', max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frigo', 'Réfrigérateur'), ('congelateur', 'Congélateur'), ('placard', 'Placard'), ('cave', 'Cave'), ('garage', 'Garage'), ('autre', 'Autre')], max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('unit', models.CharField(choices=[('piece', 'Pièce'), ('g', 'Gramme'), ('kg', 'Kilogramme'), ('ml', 'Millilitre'), ('l', 'Litre'), ('paquet', 'Paquet')], default='piece', max_length=20, verbose_name='Unité')),
                ('threshold', models.DecimalField(decimal_places=2, default=1, help_text='Quantité minimale avant ajout à la liste de courses', max_digits=10, verbose_name='Seuil minimal')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('auto_add_to_list', models.BooleanField(default=True, verbose_name='Ajout automatique à la liste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Catégorie')),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='products.location', verbose_name='Emplacement par défaut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
